export const RecipesActionTypes = {
    FETCH_RECIPES_START: 'FETCH_RECIPES_START',
    FETCH_RECIPES_SUCCESS: 'FETCH_RECIPES_SUCCESS',
    FETCH_RECIPES_FAILURE: 'FETCH_RECIPES_FAILURE'
};

export const RecipeInfoActionTypes = {
    FETCH_RECIPE_INFO_START: 'FETCH_RECIPE_INFO_START',
    FETCH_RECIPE_INFO_SUCCESS: 'FETCH_RECIPE_INFO_SUCCESS',
    FETCH_RECIPE_INFO_FAILURE: 'FETCH_RECIPE_INFO_FAILURE',
    ADD_SERVING: 'ADD_SERVING',
    DELETE_SERVING: 'DELETE_SERVING',
    ADD_TO_SHOPPING_LIST: 'ADD_TO_SHOPPING_LIST',
    DELETE_SHOPPING_LIST_ITEM: 'DELETE_SHOPPING_LIST_ITEM'
};

export const SearchActionTypes = {
    CHANGE_SEARCHFIELD: 'CHANGE_SEARCHFIELD'
};

export default {
    RecipesActionTypes,
    SearchActionTypes,
    RecipeInfoActionTypes
}

