export const RecipesActionTypes = {
    FETCH_RECIPES_START: 'FETCH_RECIPES_START',
    FETCH_RECIPES_SUCCESS: 'FETCH_RECIPES_SUCCESS',
    FETCH_RECIPES_FAILURE: 'FETCH_RECIPES_FAILURE',
};

export const RecipeInfoActionTypes = {
    FETCH_RECIPE_INFO_START: 'FETCH_RECIPE_INFO_START',
    FETCH_RECIPE_INFO_SUCCESS: 'FETCH_RECIPE_INFO_SUCCESS',
    FETCH_RECIPE_INFO_FAILURE: 'FETCH_RECIPE_INFO_FAILURE',
};

export const RecipeIngActionTypes = {
    FETCH_RECIPE_ING_START: 'FETCH_RECIPE_ING_START',
    FETCH_RECIPE_ING_SUCCESS: 'FETCH_RECIPE_ING_SUCCESS',
    FETCH_RECIPE_ING_FAILURE: 'FETCH_RECIPE_ING_FAILURE',
};

export const SearchActionTypes = {
    CHANGE_SEARCHFIELD: 'CHANGE_SEARCHFIELD'
};

export default {
    RecipesActionTypes,
    SearchActionTypes,
    RecipeInfoActionTypes
}

